/**
 * 定义常量类型
 */

// 公共
export const COM_LOADING_STATUS = 'COM_LOADING_STATUS';
export const COM_CONF = 'COM_CONF';
export const CHANGE_PATHNAME = 'CHANGE_PATHNAME';

// home
export const HOME_GET_WEATHER_CITY_DAY_LIST = 'HOME_GET_WEATHER_CITY_DAY_LIST';
export const HOME_GET_WEATHER_CITY_24H_LIST = 'HOME_GET_WEATHER_CITY_24H_LIST';
